FROM ubuntu:18.04
LABEL maintainer="juan_borges"
#RUN executa em tempo de build
RUN apt-get update && apt-get install nginx -y && rm -rf /var/lib/apt/lists/*
EXPOSE 80
COPY index.html /var/www/html/
#CMD executa em tempo de execução
WORKDIR /var/www/html
ENV APP_VERSION 2.0.0
#ENTRYPOINT = É o principal processo do container
ENTRYPOINT [ "nginx" ]
#CMD passa parâmetros para o entrypoint
CMD ["-g", "daemon off;"]
#ENTRYPOINT e CMD juntos permitem maior flexibilidade na configuração do container
#ENTRYPOINT vs CMD - Quando usar o quê?
#Use ENTRYPOINT quando você quiser que seu contêiner se comporte como um executável específico
#Use CMD para fornecer argumentos padrão para o ENTRYPOINT, que podem ser substituídos na linha de comando do docker run
#nginx -g "daemon off;" mantém o nginx rodando em primeiro plano